/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description User created, token pair returned */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description Email already registered */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login and receive token pair */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Token pair */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate refresh token and get a new token pair */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description New token pair */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weather/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current weather for a city
         * @description Cached in Redis for 15 minutes.
         */
        get: {
            parameters: {
                query: {
                    city: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current weather data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Weather"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                /** @description OpenWeatherMap API unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weather/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 5-day weather forecast for a city
         * @description Cached in Redis for 30 minutes. Returns daily aggregates.
         */
        get: {
            parameters: {
                query: {
                    city: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Forecast data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Weather"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                /** @description OpenWeatherMap API unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all alerts belonging to the authenticated user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Array of alerts (empty array if none) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Alert"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        /** Create a new alert rule */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAlertRequest"];
                };
            };
            responses: {
                /** @description Alert created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Alert"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 873cd8e5-c2b8-417d-93db-7b4d42d90b33 */
                id: string;
            };
            cookie?: never;
        };
        /** Get a specific alert by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 873cd8e5-c2b8-417d-93db-7b4d42d90b33 */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Alert data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Alert"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        /** Update an alert (partial update — only provided fields change) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 873cd8e5-c2b8-417d-93db-7b4d42d90b33 */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "threshold": 35,
                     *       "active": false
                     *     }
                     */
                    "application/json": components["schemas"]["UpdateAlertRequest"];
                };
            };
            responses: {
                /** @description Updated alert */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Alert"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        /** Delete an alert */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 873cd8e5-c2b8-417d-93db-7b4d42d90b33 */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Alert deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterRequest: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example secret123 */
            password: string;
        };
        LoginRequest: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example secret123 */
            password: string;
        };
        RefreshRequest: {
            /**
             * Format: uuid
             * @example 740885cd-4ae0-4a61-9cc3-0c08dabd0325
             */
            refresh_token: string;
        };
        TokenResponse: {
            /**
             * @description Short-lived JWT (default 1h)
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            access_token?: string;
            /**
             * Format: uuid
             * @description Long-lived opaque token for rotation
             * @example 740885cd-4ae0-4a61-9cc3-0c08dabd0325
             */
            refresh_token?: string;
            /**
             * Format: date-time
             * @example 2026-05-17T15:00:00Z
             */
            expires_at?: string;
        };
        ValidateResponse: {
            /**
             * Format: uuid
             * @example 918a6659-66e2-420b-b1d2-37122b3c4bc3
             */
            user_id?: string;
            /**
             * Format: email
             * @example user@example.com
             */
            email?: string;
            /**
             * Format: date-time
             * @example 2026-05-17T15:00:00Z
             */
            expires_at?: string;
        };
        DailyForecast: {
            /**
             * Format: date-time
             * @example 2026-05-18T00:00:00Z
             */
            date?: string;
            /**
             * Format: float
             * @description Average daytime temperature (°C)
             * @example 18.5
             */
            temp_day?: number;
            /**
             * Format: float
             * @description Average nighttime temperature (°C)
             * @example 11.2
             */
            temp_night?: number;
            /** @example Clouds */
            condition?: string;
            /**
             * Format: float
             * @description Max wind speed (m/s)
             * @example 4.4
             */
            wind_speed?: number;
            /**
             * @description Average humidity (%)
             * @example 51
             */
            humidity?: number;
            /**
             * Format: float
             * @description Max precipitation probability (0–1)
             * @example 0.23
             */
            rain_probability?: number;
        };
        Weather: {
            /** @example London */
            city?: string;
            /**
             * Format: float
             * @description Current temperature (°C)
             * @example 16.84
             */
            temperature?: number;
            /**
             * Format: float
             * @example 15.73
             */
            feels_like?: number;
            /**
             * @description OpenWeatherMap condition group
             * @example Clouds
             */
            condition?: string;
            /**
             * Format: float
             * @description Wind speed (m/s)
             * @example 5.14
             */
            wind_speed?: number;
            /**
             * @description Humidity (%)
             * @example 44
             */
            humidity?: number;
            /**
             * Format: date-time
             * @example 2026-05-17T14:02:50Z
             */
            timestamp?: string;
            /** @description Present only on /forecast endpoint */
            forecast?: components["schemas"]["DailyForecast"][];
        };
        /**
         * @description - `temp_above` — temperature exceeds threshold (°C)
         *     - `temp_below` — temperature drops below threshold (°C)
         *     - `wind_above` — wind speed exceeds threshold (m/s)
         *     - `rain`       — condition is Rain or Drizzle (threshold ignored)
         *     - `snow`       — condition is Snow (threshold ignored)
         * @enum {string}
         */
        ConditionType: "temp_above" | "temp_below" | "wind_above" | "rain" | "snow";
        Alert: {
            /**
             * Format: uuid
             * @example 873cd8e5-c2b8-417d-93db-7b4d42d90b33
             */
            id?: string;
            /**
             * Format: uuid
             * @example 918a6659-66e2-420b-b1d2-37122b3c4bc3
             */
            user_id?: string;
            /**
             * Format: email
             * @description Address to receive email notification
             * @example user@example.com
             */
            email?: string;
            /** @example London */
            city?: string;
            condition_type?: components["schemas"]["ConditionType"];
            /**
             * Format: float
             * @description Threshold value (ignored for rain/snow)
             * @example 30
             */
            threshold?: number;
            /**
             * @description Inactive alerts are stored but not checked by the worker
             * @example true
             */
            active?: boolean;
            /**
             * Format: date-time
             * @description Last time this alert fired. Null if never triggered.
             * @example null
             */
            last_triggered_at?: string | null;
            /**
             * Format: date-time
             * @example 2026-05-17T12:00:00Z
             */
            created_at?: string;
            /**
             * Format: date-time
             * @example 2026-05-17T12:00:00Z
             */
            updated_at?: string;
        };
        CreateAlertRequest: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example London */
            city: string;
            condition_type: components["schemas"]["ConditionType"];
            /**
             * Format: float
             * @description Required for all types; ignored for rain/snow
             * @example 30
             */
            threshold: number;
        };
        /** @description All fields optional. Only provided fields are updated. */
        UpdateAlertRequest: {
            /**
             * Format: email
             * @example newemail@example.com
             */
            email?: string;
            /** @example Paris */
            city?: string;
            condition_type?: components["schemas"]["ConditionType"];
            /**
             * Format: float
             * @example 35
             */
            threshold?: number;
            /** @example false */
            active?: boolean;
        };
        /** @description RFC 9457 error response */
        ProblemDetail: {
            /** @example about:blank */
            type?: string;
            /** @example Not Found */
            title?: string;
            /** @example 404 */
            status?: number;
            /** @example Alert not found. */
            detail?: string;
            /** @example /api/alerts/00000000-0000-0000-0000-000000000000 */
            instance?: string;
        };
    };
    responses: {
        /** @description Missing or invalid Bearer token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "about:blank",
                 *       "title": "Unauthorized",
                 *       "status": 401,
                 *       "detail": "Missing or malformed Bearer token."
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Resource does not belong to the authenticated user */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Validation error */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Unexpected server error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
